### ISSUE TITLE
Revisit PR 60: yaml.unsafe_load(), should we be concerned?

### ISSUE THREAD

**Issue by out0xb2** [Microsoft/mu#68]
I committed pull request #60 because we've always had this issue (i.e. load() was always unsafe).  We should revisit to determine if we care and how we might fix this if we do.

**Comment by spbrogan** [comment]
There is a policy that requires an admin to post a message to the PR before it is built.

**Comment by corthon** [comment]
I looked into it for a little bit and it seemed that the only workaround would be to drop support for some of the modules in mkdocs. While this may be considered advantageous, I also found that our threat model was...
- Risk: Code excution on the server hosting the docs and any build servers.
- Mitigation: Hosting server cannot be modified without PR acceptance by the team. **CI/PR gate servers may be exposed, since they run DocBuild on yml files submitted by the public.** It's possible that we could add a chunk to DocBuild that pre-scans the file for things that look like unsafe Python that don't fall under the category of "valid mkdocs preprocessing commands"?

**Comment by corthon** [comment]
@spbrogan, you mean that the PR gate won't even run until a comment is posted?

**Comment by spbrogan** [comment]
Yes

________________________________

**Comment by corthon** [comment]
Interesting. Haven't not known that, I might have inadvertently tripped one. Frankly, this exposure pales in comparison to the BaseTools scripts that we will just **use**.

**Comment by spbrogan** [comment]
closing this.  
PR gates are run in isolation and don't have access to credentials or secrets.  
If more needs to be done there is policy within Azure dev ops to require a project admin to enter a specified comment to run the build.  This can be done if needed.
